# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-research-backend
  namespace: legal-research
  labels:
    app: backend
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: api
    spec:
      containers:
      - name: backend
        image: legal-research-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: legal-research-config
              key: ENVIRONMENT
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: legal-research-config
              key: DEBUG
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: legal-research-config
              key: LOG_LEVEL
        - name: UPLOAD_DIRECTORY
          valueFrom:
            configMapKeyRef:
              name: legal-research-config
              key: UPLOAD_DIRECTORY
        - name: VECTORSTORE_PATH
          valueFrom:
            configMapKeyRef:
              name: legal-research-config
              key: VECTORSTORE_PATH
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: legal-research-config
              key: CORS_ORIGINS
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: legal-research-secrets
              key: GOOGLE_API_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: legal-research-secrets
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: legal-research-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: legal-research-secrets
              key: REDIS_URL
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
        - name: vectorstore-storage
          mountPath: /app/vectorstore
        - name: logs-storage
          mountPath: /app/logs
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: backend-uploads-pvc
      - name: vectorstore-storage
        persistentVolumeClaim:
          claimName: backend-vectorstore-pvc
      - name: logs-storage
        persistentVolumeClaim:
          claimName: backend-logs-pvc

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: legal-research-backend-service
  namespace: legal-research
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: backend

---
# Backend PersistentVolumeClaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads-pvc
  namespace: legal-research
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-vectorstore-pvc
  namespace: legal-research
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs-pvc
  namespace: legal-research
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
# Horizontal Pod Autoscaler for Backend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: legal-research-backend-hpa
  namespace: legal-research
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: legal-research-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
