# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: legal-research-config
  namespace: legal-research
data:
  # Backend configuration
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  UPLOAD_DIRECTORY: "/app/uploads"
  VECTORSTORE_PATH: "/app/vectorstore"
  CORS_ORIGINS: "http://localhost:3000,https://your-domain.com"
  
  # Frontend configuration
  VITE_API_BASE_URL: "http://legal-research-backend-service:8000"
  VITE_APP_NAME: "Legal Research Assistant"
  VITE_APP_VERSION: "1.0.0"

---
# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: legal-research-secrets
  namespace: legal-research
type: Opaque
data:
  # Base64 encoded values (replace with actual encoded values)
  GOOGLE_API_KEY: eW91cl9nb29nbGVfZ2VtaW5pX2FwaV9rZXlfaGVyZQ== # your_google_gemini_api_key_here
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u # your-super-secret-key-change-in-production
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXM6cG9zdGdyZXMxMjNAbGVnYWwtcmVzZWFyY2gtcG9zdGdyZXM6NTQzMi9sZWdhbF9yZXNlYXJjaA== # postgresql+asyncpg://postgres:postgres123@legal-research-postgres:5432/legal_research
  REDIS_URL: cmVkaXM6Ly86cmVkaXMxMjNAbGVnYWwtcmVzZWFyY2gtcmVkaXM6NjM3OS8w # redis://:redis123@legal-research-redis:6379/0
