# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-research-frontend
  namespace: legal-research
  labels:
    app: frontend
    component: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: ui
    spec:
      containers:
      - name: frontend
        image: legal-research-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: legal-research-config
              key: VITE_API_BASE_URL
        - name: VITE_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: legal-research-config
              key: VITE_APP_NAME
        - name: VITE_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: legal-research-config
              key: VITE_APP_VERSION
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: legal-research-frontend-service
  namespace: legal-research
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend

---
# Frontend Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: legal-research-frontend-hpa
  namespace: legal-research
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: legal-research-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
